Todoproject/TodoApp/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    path('',views.Home,name='home'),
    path('bicycle/',views.bicycle,name='bicycle'),
    path('<slug:c_slug>/',views.bicycle,name='product_by_category'),
    path('details/<int:id>',views.Details,name='details'),

]

Todoproject/Todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TodoApp.urls')), 
    path('auth/',include('userarauth.urls')), 
    path('searchapp/',include('searchapp.urls')),
    path('cartapp/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Todoproject/cartapp/urls.py
from .import views
from django.urls import path
app_name='cartapp'
urlpatterns = [
    path('addcart/<int:id>',views.addcart,name='addcart'),
    path('removecart/<int:id>',views.removecart,name='removecart'),
    path('fullremove/<int:id>',views.fullremove,name='fullremove'),
    path('displaycart/',views.displaycart,name='displaycart'),
    path('placeorder/',views.placeorder,name='placeorder'),
]

Todoproject/searchapp/urls.py
from django.urls import path
from . import views
app_name='searchapp'
urlpatterns = [
    path('searchproduct/',views.SearchResult,name='searchproduct'),
]

Todoproject/userarauth/urls.py
from django.urls import path
from.import views

app_name='auth'
urlpatterns = [
    path('register/',views.registerUser,name='register'),
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),

    
    
]

Todoproject/TodoApp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('name',)
        
        
    def __str__(self):
        return self.name
    def get_url(self):
        return reverse('shop:product_by_category',args=[self.slug])


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='product',blank=True)
    price=models.DecimalField(max_digits=8,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    class Meta:
        ordering=('name',)
        
        
    def __str__(self):
        return self.name

Todoproject/cartapp/models.py
from django.db import models
from TodoApp.models import Product

# Create your models here.
class Cart(models.Model):
    user=models.CharField(max_length=200)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    class Meta:
        db_table='cart'
        

Todoproject/searchapp/models.py
from django.db import models

# Create your models here.

Todoproject/userarauth/models.py
from django.db import models

# Create your models here.

Todoproject/TodoApp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product,Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def Home(request):
    return render(request,'index.html')


def bicycle(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        
        product_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        product_list=Product.objects.all().filter(available=True) 
        #PAGINATOR
    
    paginator=Paginator(product_list,50)
    
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
        
    #FOR INAVLID PAGE AND EMPTY PAGE
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
        
           
    return render(request,'bicycle.html',{'data':product_list,'category':c_page,'products':products})



def Details(req,id):
    data=Product.objects.get(id=id)
    return render(req,'details.html',{'data':data})

Todoproject/cartapp/views.py
from django.shortcuts import render,redirect
from TodoApp.models import Product
from.models import Cart
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def addcart(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    print(product)
    try:
        cart=Cart.objects.get(product=product)
        if cart.quantity<cart.product.stock:
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,product=product,quantity=1)
    return redirect('cartapp:displaycart')

def displaycart(req):
    user=req.session['user']
    cart=Cart.objects.all().filter(user=user)
    total=sum(cart.product.price * cart.quantity for cart in cart) - 1020
    return render(req,'cart.html',{'cart':cart,'total':total})




def removecart(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    cart=Cart.objects.get(product=product,user=user)
    if cart.quantity>1:
        cart.quantity-=1
        cart.save()
    return redirect('cartapp:displaycart')
    

def fullremove(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    cart=Cart.objects.get(product=product,user=user)
    cart.delete()
    return redirect('cartapp:displaycart')


def placeorder(req):
    user=req.session['user']
    cart=Cart.objects.filter(user=user)
    for cart in cart:
        prod=Product.objects.get(id=cart.product.id)
        prod.stock-=cart.quantity
        prod.save()
        cart.delete()
    return redirect('shop:home')

Todoproject/searchapp/views.py
from django.shortcuts import render
from TodoApp.models import Product
from django.db.models import Q

# Create your views here.

def SearchResult(req):
    products=None
    query=None
    if 'q' in req.GET:
        query=req.GET.get('q')
        print(query)
        products=Product.objects.all().filter(Q(name__contains=query)| Q(desc__contains=query))
        return render(req,'search.html',{'query':query,'products':products})

Todoproject/userarauth/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.

def registerUser(req):
    if req.method=='POST':
        fname=req.POST.get("fname","")
        lname=req.POST.get("lname","")
        email=req.POST.get("email","")
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        cpassword=req.POST.get("cpassword","")
        print(fname,lname,email,username,password,cpassword)
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(req,"username already exist")
                return redirect('auth:register')
            elif User.objects.filter(email=email).exists():
                messages.info(req,"email already exist")
                return redirect('auth:register')
            else:
                user=User.objects.create_user(first_name=fname,last_name=lname,email=email,username=username,password=password)
                user.save()
                return redirect('auth:login')
        else:
            messages.info(req,"password not matched")
            return redirect('auth:register')
    return render(req, 'registeruser.html')
def loginUser(req):
    if req.method=='POST':
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        user=auth.authenticate(username=username,password=password)
        # print(user)
        if user is not None:
          auth.login(req,user)
          print(user)
          req.session['user']=str(user)
          return redirect('shop:home')
        else:
            messages.info(req, "invalidcredentials")
            return redirect('auth:login')
       
    return render(req, 'loginuser.html')


def logoutUser(req):
    auth.logout(req)
    req.session.pop('user',None)
    return redirect('shop:home')

Todoproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
  </head>
  <body>
    {% include 'nav.html' %}
    {% block content %}

    {% endblock %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

Todoproject/templates/bicycle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mb-3">
  {% if category %}
  <h1 class="hed mt-5 mb-2">{{category.name}}</h1>
  <img class="can rounded-5 " src="{{category.image.url}}" style="margin-left: 700px;" width="20%" height="370" alt="">
  <h5 class="des mt-4 mb-5">{{category.desc}}</h5>
  <link rel="stylesheet" href="{% static 'css\style.css' %}">
  {% else %}
  {% endif %}




  <div class="container-fluid mb-3">
    <h1 class="hed mt-5 mb-2" style="margin-left: 50px; font-size: 55px;">NEW TREK MODELS</h1>
  </div>




  <div class="rw row d-flex">
    <div class="col-lg-6 col-md-2 col-sm-12">
      <img class=" " src="../static/images/18-18.png" width="590px" height="220px" style="margin-left:320px;" alt="...">
    </div>
    <div class="col-lg-6 col-md-2 col-sm-12">
      <img class=" " src="../static/images/15.jpg" width="570px" height="220px" alt="...">
    </div>
  </div>

  <div class="rw row d-flex">
    <div class="col-lg-6 col-md-2 col-sm-12">
      <img class=" " src="../static/images/18.jpg" width="590px" height="220px"
        style="margin-top:20px; margin-left: 320px;" alt="...">
    </div>
    <div class="col-lg-6 col-md-2 col-sm-12">
      <img class=" " src="../static/images/12.png" width="570px" height="220px" style="margin-top:20px;" alt="...">
    </div>
  </div>










  <div class="container-fluid mb-3">
    <h1 class="hed mt-5 mb-2" style="margin-left: 50px; font-size: 55px;">In Stock Bikes</h1>
  </div>
  <div class="container-fluid d-flex justify-content-center">
    <div class="card-group mb-3">
      {% for i in products %}
      {% if i.available %}
      <a href="{% url 'shop:details' i.id %}">
        <div class="cad border p-5 mb-5 bg-body rounded mb-4 me-2 shadow">
          <img src="{{i.image.url}}" height="150px" class="card-img-top rounded-4 " alt="...">
          <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            <h5 class="card-text">${{i.price}}</h5>
            <h6 class="card-text">{{i.category}}</h6>
          </div>
        </div>
      </a>

  {% endif %}
  {% endfor %}
    </div>
  </div>




  {% endblock %}

Todoproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="rw row mt-4 mb-5">
    <div class="col-lg-8 btn-light">
        <h5 class="fr">from saved Address</h5>
    {% for cartitem in cart %}
    <div class="rrw row border w-100 shadow">
        <div class="col-lg-4 col-md-3 col-sm-12">
            <img class="crtimg mt-2 shadow" src="{{cartitem.product.image.url}}" alt="">

            <h4 class="qt mt-4"><a href="{% url 'cartapp:removecart' cartitem.product.id %}"
                class="btn">-</a>{{cartitem.quantity}}<a href="{% url 'cartapp:addcart' cartitem.product.id %}" class="btn">+</a>
            </h4>
        </div>
        <div class="col-lg-8 border mt-2 mb-2">
            <h5 class="pro mt-3">{{cartitem.product}}</h5>
            <h6 class="des">{{cartitem.product.desc}}</h6>
            <h4 class="pr">${{cartitem.product.price}}</h4>
        </div>
        <div class="col-lg-2">
            <a href="{% url 'cartapp:fullremove' cartitem.product.id %}" class="cn btn btn-danger">Remove</a>
        </div>
    </div>
    {% endfor %}
    {% if cart %}
    <a href="{% url 'shop:home' %}" class="purch btn btn-primary mt-3 pt-2 pb-2">
        <h6>continue purchase</h6>
    </a>   
    </div>
    <div class="to col-lg-4 fixed-end border">
        <div class="pp row border">
            <h3>PRICE DETAILS</h3>
        </div>
        <div class="cc col-lg-12">
            <h4 class="ds mt-3">DISCOUNT<span class="dss mt-3">-$1020</span></h4>
            <h4 class="TOT mt-5">TOTAL AMOUNT<span class="tt">-${{total}}</span></h4><hr>
            <h5 class="sav">you will save $1,020 on this order</h5>
        </div>
        <a href="{% url 'cartapp:placeorder' %}" class="plac btn btn-warning pt-2 mb-3"><h4>placeorder</h4></a>
        {% else %}
        <a href="{% url 'shop:home' %}"><h5 class="prpr">please purchase your product</h5></a>
        {% endif %}
    </div>
</div>
{% endblock %}

Todoproject/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="conta container-fluid mb-3 justify-content-center  d-flex ">
    <div class="card crd rounded-2  ms-4 w-50 me-4 mb-5 mt-3"style="border:0;">
        <div class="row">
            <h2 class="hed2">{{data.name}}</h2>
            <div class="cd card shadow-lg p-3 mb-5 p-3 mb-5 bg-body rounded mb-4">
                <img src="{{data.image.url}}" class="card-img-top rounded-2 ms-2 mt-3" alt="...">
                <div class="card-body">
                
      
                
                </div>
            </div>
         


                <div class="col2 col-5 ms-4">
                    <h2>{{data.name}}</h2>
                    <h5>{{data.desc}}</h5>
                    <div class="coo">
                    <h3>${{data.price}}</h3></div>
                    <h5 class="ct mt-3">category: {{data.category}}</h5>    
                    <h5>created date:{{data.created}}</h5> 
                    <h5 class="up mb-4">updated date: {{data.updated}}</h5>   

                    {% if data.stock >= 1 %}
                    <a href="{% url 'cartapp:addcart' data.id %}" type="button" class="btn btn-warning me-3 p-2">Add to cart</a>
                   
                    {% else %}
                    <span><h3 class="out" style="color: green;">out of stock</h3></span>
                    {% endif %}
            </div>
          </div>
    </div>
        
</div>

{% endblock %} 

Todoproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mb-3">
  {% if category %}
 <h1 class="hed mt-5 mb-2">{{category.name}}</h1>
 <img class="can rounded-5 " src="{{category.image.url}}" style="margin-left: 700px;" width="26%" height="450" alt="">
 <h5 class="des mt-4 mb-5">{{category.desc}}</h5>
 <link rel="stylesheet" href="{% static 'css\style.css' %}">
 {% else %}
</div>
 

 <img class="can " src="../static/images/bycycle.jpg" style="margin-left: 300px;" width="65%" height="500" style="margin-top: 200px;" alt="">
 {% endif %}
<div class="container-fluid d-flex justify-content-center">
    <div class="card-group mb-3">
      {% for i in products %}
        {% if i.available %}
        <a href="{% url 'shop:details' i.id %}">
        <div class="cad border p-5 mb-5 bg-body rounded mb-4 me-2 shadow">
          <img src="{{i.image.url}}" height="150px" class="card-img-top rounded-4 " alt="...">
          <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            <h5 class="card-text">${{i.price}}</h5>
            <h6 class="card-text">{{i.category}}</h6>
          </div>
        </div>
        </a>
        
        {% endif %}
        {% endfor %}


     
      </div>
</div>



<div class="container-fluid mb-3">
  <h1 class="hed mt-5 mb-2" style="margin-left: 50px; font-size: 55px;">NEW TREK MODELS</h1>
</div>




<div class="rw row d-flex">
<div class="col-lg-6 col-md-2 col-sm-12">                     
  <img class=" " src="../static/images/kaaa.webp" width="590px" height="220px" style="margin-left:320px;" alt="...">
</div>  
<div class="col-lg-6 col-md-2 col-sm-12">
  <img class=" " src="../static/images/byyyy.webp" width="570px" height="220px" alt="...">
</div>  
</div>

<div class="rw row d-flex">
<div class="col-lg-6 col-md-2 col-sm-12">
<img class=" " src="../static/images/laaa.webp" width="590px" height="220px" style="margin-top:20px; margin-left: 320px;" alt="...">
</div>  
<div class="col-lg-6 col-md-2 col-sm-12">
<img class=" " src="../static/images/maa.webp" width="570px" height="220px" style="margin-top:20px;" alt="...">
</div>  
</div>






<div class="container"  style="margin-right: 1000px; margin-top: 40px;">
  <img src="../static/images/WhyElectric.jpg"alt="">
</div>


<div class="container-fluid mb-3">
  <h1 class="hed mt-5 mb-2" style="margin-left: 50px; font-size: 40px;">PROFESSONAL SERVISES</h1>
</div>


<div class="rw row d-flex">
  <div class="col-lg-4 col-md-2 col-sm-12">                     
    <img class=" " src="../static/images/wheel5.jpg" width="600px" height="180px" alt="...">
  </div>  
  <div class="col-lg-4 col-md-2 col-sm-12">                     
    <img class=" " src="../static/images/wheel6.jpg"  style="margin-left: 35px" width="600px" height="180px" alt="...">
  </div> 
  <div class="col-lg-4 col-md-2 col-sm-12">                     
    <img class=" " src="../static/images/wheel3.webp" style="margin-left: 70px" width="600px" height="180px" alt="...">
  </div> 
</div>  





<div class="container-fluid mt-5">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199525.66312872447!2d-90.62931050546875!3d38.612340900000014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87d8caf65cc0089b%3A0xe73b343b5831ee5b!2sMaplewood%20Bicycle!5e0!3m2!1sen!2sin!4v1708661603464!5m2!1sen!2sin" width="2000" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>



<div class="container-fluid mb-3">
  <h1 class="hed mt-5 mb-2" style="margin-left: 50px; font-size: 45px;">- THE SHOP -</h1>
</div>
<h5 class="des mt-4 mb-5">
  We are very proud to be part of our cycling community since 1973!</br>
  We are bike geeks plain and simple. We love what we do. We sweat the details. </br>
  We commute, we race, we ride with our kids, we ride charity events, we do multi-sport, we get dirty, we get bloody, and tomorrow we will wake up and do it all over again!</h5>
  <div class="container-fluid mb-3">
    <h1 class="hed mt-5 mb-2" style="margin-left: 50px; font-size: 75px;">Join  Our  Team</h1>
  </div>


<div>
    <button type="START HERE" class="btn btn-danger" style="margin-left: 800px; font-size: 35px; margin-bottom: 20px; margin-top: 20px;">START HERE</button>
</div>

<!-- <div class="paginator mx-auto">
  {% if products.paginator.num_pages > 1 %}<hr>
    <div class="text-center">
      {% for pg in products.paginator.page_range %}
      <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active {% endif %}">{{pg}}</a>
      {% endfor %}
    </div>
  {% endif %} -->

</div>



{% endblock %}

Todoproject/templates/nav.html
<!-- <nav class="navbar bg-light bg-dark">
  <div class="container-fluid">
    


    <form class="d-flex" role="search"  action="{% url 'searchapp:searchproduct' %}" method="GET">
      <input class="form-control me-2 mt-4 "name="q" type="search" style="margin-left: 750px;" placeholder="Search" aria-label="Search">
      <img class="search mt-4" src="../static/images/search12.png" width="40" style="color: white;" alt="">
      <a class="pt-4" href="" style="padding-left: 640px;"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path fill="yellow" d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z"/></svg></a>
   
     
    </form>
    {% if user.is_authenticated %}

    <span class="text-light">{{user}}</span> 
  <li class="nav-item ">
    <a class="nav-link nav-signup btn btn-light mb-lg-0 mb-2 " href="{% url 'auth:logout' %}"><b>Logout</b></a>
  </li>

  {% else %}
  <li class="nav-item ">
    <a class="nav-link nav-signup btn btn-light ps-2 pe-2 px-2 py-2 pt-1" style="margin-left: 530px; " href="{% url 'auth:register' %}"><b>Sign up</b></a>
  </li>
  <li class="nav-item ">
    <a class="nav-bttn btn btn-light mt-4" style="margin-right: 100px;" href="{% url 'auth:login' %}"><b>Log
        in</b></a>
  </li>
  {% endif %}
    
  </div>
</nav>






<nav class="navbar navbar-expand-lg bg-secondary">
<div class="container-fluid">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          category
        </a>

        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'shop:home' %}">All Product</a></li>

          {% for link in links %}
          <li><a class="dropdown-item" href="{{link.get_url}}">{{link.name}}</a></li>

          {% endfor %}

        </ul>

       
        


      </li>

    </ul>
    


  </div>
</div>
</nav>
 -->






 {% load static %}
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container-fluid">
     <a class="navbar-brand" href="#"></a>
     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}"><h1>MAPLEWOOD</h1></a>
                     
           <div>
             <button type="" class="btn btn-danger" style="margin-left: 40px; font-size: 20px; padding-top: 1px; padding-bottom: 1px; background-color: red;">BICYCLE</button>
           </div>
         </li>
 
 
 
         <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}" style="margin-top: 40px; margin-left: 50px;">Home</a>
         </li>
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:bicycle' %}" style="margin-top: 40px; margin-left: 50px;">bicycle</a>
        </li>

 
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
             aria-expanded="false" style="margin-top: 40px; margin-left: 50px;">
             Category
           </a>
           <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             <li><a class="dropdown-item" href="{% url 'shop:bicycle' %}">ALL products</a></li>
             {% for link in links %}
             <li><a class="dropdown-item" href="{{link.get_url}}">{{link.name}}</a></li>
 
             {% endfor %}
 
           </ul>
         </li>
       </ul>
 
       <form class="d-flex" role="search" action="{% url 'searchapp:searchproduct' %}" method="GET">
         <input class="form-control me-2 mt-3 mb-3" type="search"  name="q" placeholder="Search" aria-label="Search">
 
         <a class="pt-4" href=""><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="40"><path fill="yellow" d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z"/></svg></a>  
       </form>
 
       <div class="d-flex">
         {% if user.is_authenticated %}
 
         <span class="text-light">{{user}}</span>
         <a href="{% url 'auth:logout' %}" class="btn btn-outline-danger " type="button">Logout</a>
         {% else %}
         <a href="{% url 'auth:login' %}" class="btn btn-outline-light me-2" type="button">Login</a>
         <a href="{% url 'auth:register' %}" class="btn btn-outline-light me-2" type="button">Signup</a>
         
         {% endif %}
       </div>
     </div>
   </div>
 </nav>

Todoproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="card-group mb-3">
      
      {% for i in products %}
      
        <a href="{% url 'shop:details' i.id %}">
        <div class="cad border p-3 mb-5 bg-body rounded mb-4 me-2 mr-5">
          <img src="{{i.image.url}}" height="200px" width="600px" class="card-img-top rounded-4 " alt="...">
          <div class="card-body">
            <h3 class="card-title">{{i.name}}</h3>
            <h5 class="card-text">${{i.price}}</h5>
            <h6 class="card-text">{{i.category}}</h6>
          </div>
        </div>
        </a>
       
        {% endfor %}

      </div>
</div>
{% endblock %}